import { fileURLToPath } from 'node:url';
import { createDatabase, migrateToLatest } from '@fd/chassis-postgres';
import { startPostgresContainer, type StartedPostgres } from '@fd/chassis-testing';
import { Cli, TypeScriptSerializer } from 'kysely-codegen';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { orderMigrationSources } from './order-migration-sources.config.ts';

const generatedTypesFile = fileURLToPath(new URL('./generated/database.ts', import.meta.url));

let postgres: StartedPostgres;
let appliedMigrations: readonly string[];

beforeAll(async () => {
  postgres = await startPostgresContainer();
  const database = createDatabase({
    connectionString: postgres.connectionUri,
    maximumConnectionCount: 1,
    onConnectionError: () => undefined,
  });
  appliedMigrations = await migrateToLatest(database, orderMigrationSources);
  await database.destroy();
});

afterAll(async () => {
  await postgres.stop();
});

describe('orderMigrationSources', () => {
  it('applies the outbox, inbox and order migrations', () => {
    expect(appliedMigrations).toEqual([
      'inbox/0001-create-inbox-table',
      'order/0001-create-menu-items-table',
      'order/0002-seed-menu-items',
      'order/0003-create-orders-table',
      'order/0004-create-idempotency-keys-table',
      'order/0005-create-saga-instances-table',
      'outbox/0001-create-outbox-table',
    ]);
  });

  it('matches the committed database types (UPDATE_GOLDEN=1 rewrites them)', async () => {
    const generation = new Cli().generate({
      url: postgres.connectionUri,
      camelCase: true,
      typeMapping: { int8: 'bigint' },
      excludePattern: '{inbox,outbox,kysely_*}',
      serializer: new TypeScriptSerializer({ skipAutogeneratedFileComment: true }),
      outFile: generatedTypesFile,
      verify: process.env['UPDATE_GOLDEN'] !== '1',
      logLevel: 'silent',
    });

    await expect(generation).resolves.toContain('export interface DB');
  });
});
