import { cp, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { inboxMigrations } from '@fd/chassis-inbox';
import { outboxMigrations } from '@fd/chassis-outbox';
import { createDatabase, migrateToLatest } from '@fd/chassis-postgres';
import { startPostgresContainer, type StartedPostgres } from '@fd/chassis-testing';
import { sql, type Kysely } from 'kysely';
import { Cli, TypeScriptSerializer } from 'kysely-codegen';
import { afterAll, beforeAll, describe, expect, it, onTestFinished } from 'vitest';
import { orderMigrationSources } from './order-migration-sources.config.ts';

interface SagaDeadlineRow {
  readonly sagaId: string;
  readonly hasDeadline: boolean;
  readonly isDue: boolean;
}

interface DeliveryFeeRow {
  readonly deliveryFeeInCents: bigint;
  readonly totalInCents: bigint;
}

const generatedTypesFile = fileURLToPath(new URL('./generated/database.ts', import.meta.url));
const orderMigrationsDirectory = fileURLToPath(new URL('./migrations/', import.meta.url));

let postgres: StartedPostgres;
let appliedMigrations: readonly string[];

function openDatabase(databaseName: string): Kysely<unknown> {
  const databaseUrl = new URL(postgres.connectionUri);
  databaseUrl.pathname = `/${databaseName}`;
  return createDatabase({
    connectionString: databaseUrl.toString(),
    maximumConnectionCount: 1,
    onConnectionError: () => undefined,
  });
}

async function copyOrderMigrationsWithout(excludedFileName: string): Promise<URL> {
  const directory = await mkdtemp(join(tmpdir(), 'order-migrations-'));
  onTestFinished(() => rm(directory, { recursive: true }));
  await cp(orderMigrationsDirectory, directory, {
    recursive: true,
    filter: (source) => !source.endsWith(excludedFileName),
  });
  return pathToFileURL(`${directory}/`);
}

beforeAll(async () => {
  postgres = await startPostgresContainer();
  const database = createDatabase({
    connectionString: postgres.connectionUri,
    maximumConnectionCount: 1,
    onConnectionError: () => undefined,
  });
  appliedMigrations = await migrateToLatest(database, orderMigrationSources);
  await database.destroy();
});

afterAll(async () => {
  await postgres.stop();
});

describe('orderMigrationSources', () => {
  it('applies the outbox, inbox and order migrations', () => {
    expect(appliedMigrations).toEqual([
      'inbox/0001-create-inbox-table',
      'order/0001-create-menu-items-table',
      'order/0002-seed-menu-items',
      'order/0003-create-orders-table',
      'order/0004-create-idempotency-keys-table',
      'order/0005-create-saga-instances-table',
      'order/0006-add-order-rejection',
      'order/0007-add-compensated-saga-status',
      'order/0008-move-payment-token-out-of-saga-order',
      'order/0009-add-timeout-rejection-reasons',
      'order/0010-require-deadlines-of-running-sagas',
      'order/0011-replace-menu-items-with-restaurant-menus',
      'order/0012-add-order-delivery-fee',
      'outbox/0001-create-outbox-table',
    ]);
  });

  it('matches the committed database types (UPDATE_GOLDEN=1 rewrites them)', async () => {
    const generation = new Cli().generate({
      url: postgres.connectionUri,
      camelCase: true,
      typeMapping: { int8: 'bigint' },
      excludePattern: '{inbox,outbox,kysely_*}',
      serializer: new TypeScriptSerializer({ skipAutogeneratedFileComment: true }),
      outFile: generatedTypesFile,
      verify: process.env['UPDATE_GOLDEN'] !== '1',
      logLevel: 'error',
    });

    await expect(generation).resolves.toContain('export interface DB');
  });

  it('gives every running saga saved without a deadline one that is already due', async () => {
    const administration = openDatabase('postgres');
    onTestFinished(() => administration.destroy());
    await sql`create database deadline_backfill`.execute(administration);
    const database = openDatabase('deadline_backfill');
    onTestFinished(() => database.destroy());
    const migrationsBeforeDeadlines = await copyOrderMigrationsWithout(
      '0010-require-deadlines-of-running-sagas.sql',
    );
    await migrateToLatest(database, [
      outboxMigrations,
      inboxMigrations,
      { name: 'order', directory: migrationsBeforeDeadlines },
    ]);
    await sql`
      insert into saga_instances (
        saga_id, saga_type, order_id, step, state, version, status, deadline_at
      ) values
        ('0199a5d0-0000-7000-8000-0000000000b1', 'PlaceOrderSaga',
          '0199a5d0-0000-7000-8000-0000000000a1', 'REJECTING_TICKET', '{}', 3, 'RUNNING', null),
        ('0199a5d0-0000-7000-8000-0000000000b2', 'PlaceOrderSaga',
          '0199a5d0-0000-7000-8000-0000000000a2', 'COMPLETED', '{}', 5, 'COMPLETED', null)
    `.execute(database);

    const backfill = await migrateToLatest(database, orderMigrationSources);

    const rows = await sql<SagaDeadlineRow>`
      select saga_id, deadline_at is not null as has_deadline,
        coalesce(deadline_at <= now(), false) as is_due
      from saga_instances order by saga_id
    `.execute(database);
    expect(backfill).toEqual(['order/0010-require-deadlines-of-running-sagas']);
    expect(rows.rows).toEqual([
      { sagaId: '0199a5d0-0000-7000-8000-0000000000b1', hasDeadline: true, isDue: true },
      { sagaId: '0199a5d0-0000-7000-8000-0000000000b2', hasDeadline: false, isDue: false },
    ]);
  });

  it('gives every order placed before the delivery fee a fee of zero, so its total stays its items', async () => {
    const administration = openDatabase('postgres');
    onTestFinished(() => administration.destroy());
    await sql`create database delivery_fee_backfill`.execute(administration);
    const database = openDatabase('delivery_fee_backfill');
    onTestFinished(() => database.destroy());
    const migrationsBeforeDeliveryFee = await copyOrderMigrationsWithout(
      '0012-add-order-delivery-fee.sql',
    );
    await migrateToLatest(database, [
      outboxMigrations,
      inboxMigrations,
      { name: 'order', directory: migrationsBeforeDeliveryFee },
    ]);
    await sql`
      insert into orders (
        order_id, consumer_id, restaurant_id, total_in_cents, currency, delivery_street,
        delivery_number, delivery_city, delivery_postal_code, placed_at, version, status
      ) values (
        '0199a5d0-0000-7000-8000-0000000000a1', '0199a5d0-0000-7000-8000-0000000000c1',
        '0199a5d0-0000-7000-8000-000000000001', 9800, 'BRL', 'Rua Augusta', '1500',
        'Sao Paulo', '01304-001', now(), 1, 'APPROVAL_PENDING'
      )
    `.execute(database);

    const backfill = await migrateToLatest(database, orderMigrationSources);

    const rows = await sql<DeliveryFeeRow>`
      select delivery_fee_in_cents, total_in_cents from orders
    `.execute(database);
    expect(backfill).toEqual(['order/0012-add-order-delivery-fee']);
    expect(rows.rows).toEqual([{ deliveryFeeInCents: 0n, totalInCents: 9800n }]);
  });
});
